name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Set up Go
        uses: actions/setup-go@v4.0.1
        with:
          go-version: '1.20'

      - name: GoRelease
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release --clean
          workdir: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-artifact@v2
        with:
          name: wetlog
          path: dist/wetlog