name: build and test wetlog code

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Set up Go
        uses: actions/setup-go@v4.0.1
        with:
          go-version: '1.20'

      - name: Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53

      - name: Vet
        run: |
          go vet ./...

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v ./...